version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes: 
    - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: AkkiBarModiSarkar
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\":\"HS256\",\"key\":\"MaaMatiManushMaaMatiManushMaaMatiManushMaaMatiManushMaaMatiManush\"}"
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    environment:
      FLASK_DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/postgres
      PORT: 3000
      SECRET_KEY: MaaMatiManushMaaMatiManushMaaMatiManushMaaMatiManushMaaMatiManush